# Torch Tensors
For the full documentation, see [here](https://pytorch.org/docs/stable/tensors.html).

In [ ]:
import torch
import numpy as np

Every Tensor has a _torch.dtype_, a _torch.device_ and _torch.layout_.

In [30]:
t = torch.tensor(3)
print(t.dtype)
print(t.device)
print(t.layout) # Layout is either strided (dense) or sparse_coo (sparse). 

torch.int64
cpu
torch.strided


In [12]:
# Tensor can be constructed from a list:
classic_list = [[1, -1], [2, 1]]

t1 = torch.tensor(classic_list)
t2 = torch.tensor(np.array(classic_list))

print(t1)
print(t1 == t2) # Compare values elementwise
print(t1 * 2) # Scalar multiplication
print(t1 @ (t1 - 1)) # Matrix multiplication using @

single = torch.tensor(3)
print(single.item()) # We can retrieve single tensor value using .item()

tensor([[ 1, -1],
        [ 2,  1]])
tensor([[True, True],
        [True, True]])
tensor([[ 2, -2],
        [ 4,  2]])
tensor([[-1, -2],
        [ 1, -4]])
3


Tensors are similar to NumPy's ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing. Most of the operations that can be performed on NumPy arrays can also be performed on Tensors.

In [26]:
a = torch.arange(40)
b = torch.reshape(a, (8,5)) # Reshape changes the dimensions of the tensor.
c = torch.reshape(b, (10, 4)) # Note that the product of the dimension must equal the original count.
print(c)

matmul = c.T @ c # We can take the transpose of a tensor using T

# Many functions on torch also work directly on the tensor:
d = a.reshape((40,1))
print(d.T)


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
         36, 37, 38, 39]])
